const excusesList = [
    "Root Cause: A hamster chewed through the main optical cable. Technicians are currently feeding it. 🐹",
    "Root Cause: The website's AI submitted a vacation request and is currently relaxing on a virtual beach. 🌴",
    "Root Cause: This page exists, but only in an alternate dimension. Please recalibrate your quantum tuner. 🌌",
    "Root Cause: Spilled coffee onto the primary mainframe. The server is still shaking from the caffeine. ☕",
    "Root Cause: The administrator took the code home and accidentally left it on the public bus. 🚌",
    "Root Cause: Critical disruption in the space-time continuum. Please take three steps away from the monitor. 🕳️",
    "Root Cause: Solar flares are actively reorganizing our data index packages into random emojis. ☀️",
    "Root Cause: The server gnome is currently sleeping on the requested database sector. 🧝",
    "Root Cause: A rogue pixel escaped its rendering queue and caused a cascade failure. 🔲",
    "Root Cause: The cloud storage is actually just someone's laptop named 'Cloud'. It crashed. 💻",
    "Root Cause: Our firewall caught a cold and blocked all legitimate traffic by accident. 🤧",
    "Root Cause: The database forgot its own password and locked itself out permanently. 🔐",
    "Root Cause: An intern unplugged the 'server' thinking it was a space heater. ❄️",
    "Root Cause: The CDN got lost trying to find its way back from the content delivery trip. 🗺️",
    "Root Cause: DNS servers are undergoing existential therapy. They question their purpose. 🧘",
    "Root Cause: The load balancer distributed traffic unevenly, now one server is depressed. ⚖️",
    "Root Cause: A backup generator tried to backup a file that was already backed up. 🔄",
    "Root Cause: The cache expired so aggressively it deleted itself along with everything else. 🗑️",
    "Root Cause: Our uptime monitoring service is down, ironically monitoring its own outage. 📉",
    "Root Cause: A microservice had a microbreakdown. It's taking a micro-vacation. 🔬",
    "Root Cause: The API received too many compliments and decided to take a nap. 😴",
    "Root Cause: Bandwidth ran out halfway through loading this error message. You got cut off mid-crisis. 📶",
    "Root Cause: SSL certificates got confused about which identity to prove during verification. 🛂",
    "Root Cause: Git merge conflict on production. Someone typed 'theirs' instead of 'ours'. 🌳",
    "Root Cause: The web socket disconnected to go do some soul-searching. It'll be back. 🔌",
    "Root Cause: Container orchestration failed because the containers refused to dock. ⚓",
    "Root Cause: Load testing was too successful. The system now fears actual traffic. 🏋️",
    "Root Cause: The motherboard went on strike demanding better working conditions. ⚡",
    "Root Cause: We're experiencing an unexpected shortage of zeros and ones. 📊",
    "Root Cause: The router thinks it's a fish and needs water. 🐟",
    "Root Cause: A meteorite narrowly missed our data center, but scared the servers badly. ☄️",
    "Root Cause: The keyboard sent us a strongly worded letter. We're negotiating. ⌨️",
    "Root Cause: Cat walked across the server during critical update. Damage assessment ongoing. 🐱",
    "Root Cause: The firewall is having an identity crisis. Is it fire? Is it wall? Nobody knows. 🤷",
    "Root Cause: Server room temperature reached 'slightly warm' levels. Panic ensued. 🌡️",
    "Root Cause: The database is on a digital detox and refusing to connect. 📵",
    "Root Cause: Our IT department is currently being held hostage by ransomware. Just kidding, they're at lunch. 🥪",
    "Root Cause: The page got stuck in traffic on the information superhighway. 🛣️",
    "Root Cause: Binary code went on hunger strike. We're trying to feed it more bits. 🍔",
    "Root Cause: The hosting company's power went out, but the lights stayed on, confusing everyone. 💡",
    "Root Cause: An alien signal corrupted our CSS. Now everything looks extraterrestrial. 👽",
    "Root Cause: The webpage went on a journey of self-discovery and forgot where it lives. ✨",
    "Root Cause: Our servers are speaking in riddles today. Try asking them nicer questions. 🎭",
    "Root Cause: The internet decided to take a mental health day. It's been stressed lately. 🧠",
    "Root Cause: A ghost in the machine is haunting our database tables. 👻",
    "Root Cause: The HTML tag got lost looking for its closing sibling. Family drama. 👨‍👩‍👦",
    "Root Cause: Cloud provider's cloud literally turned into rain. Servers flooded. ☁️",
    "Root Cause: The API key was stolen by a cyber-ninja. We're tracking them down. 🥷",
    "Root Cause: Quantum entanglement glitched and the page is now in two places at once. ⚛️",
    "Root Cause: Our developer's coffee cup tipped over during commit. Code is soggy. ☕",
    "Root Cause: The server thinks it's Tuesday when it's actually Friday. Confused days. 📅",
    "Root Cause: WiFi waves are interfering with each other. Creating digital storm. ⛈️",
    "Root Cause: The URL became shy and hid behind the http prefix. 😳",
    "Root Cause: A butterfly flapped its wings in China and our server farm collapsed. 🦋",
    "Root Cause: The login form fell in love with the logout button and eloped. 💕",
    "Root Cause: Our backup server backed up so much it became a hoarder. Can't fit anything else. 📦",
    "Root Cause: The database is going through a rebellious phase. Ignores all queries. 🤬",
    "Root Cause: Someone accidentally pressed the universe's delete button. Cosmic mistake. 🌌",
    "Root Cause: The cache memory had an existential crisis and emptied itself. Philosophical moment. 🤔",
    "Root Cause: Our servers are powered by hamsters. They're tired today. Running wheel jammed. 🐭",
    "Root Cause: The internet explorer (yes, really) showed up uninvited and broke things. 🌐",
    "Root Cause: A time traveler from the future deleted this page to save us from ourselves. ⏰",
    "Root Cause: The CSS styles went on vacation without telling the HTML. Awkward breakup. 👢",
    "Root Cause: Our servers are listening to heavy metal music and got distracted by the guitar solos. 🎸",
    "Root Cause: The JavaScript interpreter decided to interpret literally. No creativity allowed. 🤖",
    "Root Cause: A digital virus is making everything feel sick. Prescribed bed rest. 🦠",
    "Root Cause: The server farm's wifi-connected chickens laid eggs that crashed the system. 🐔",
    "Root Cause: Our firewall is afraid of hackers and locked itself in panic mode. 🚪",
    "Root Cause: The database indexes got tangled like headphones in a pocket. Unraveling slowly. 🎧",
    "Root Cause: Someone's smart fridge is spamming requests and overwhelming our servers. 🧊",
    "Root Cause: The web server is practicing mindfulness and ignoring incoming requests for inner peace. 🧘",
    "Root Cause: Our CDN is delivering clouds instead of content. Weather-dependent service. 🌧️",
    "Root Cause: The code underwent a spiritual transformation and transcended physical existence. 🙏",
    "Root Cause: A typo in the production server created a parallel universe where this page doesn't exist. 🌀",
    "Root Cause: The server is currently training for a marathon. Too busy running to serve pages. 🏃",
    "Root Cause: Our hosting provider's hosting provider's hosting provider is down. Infinite nesting failure. 🎭",
    "Root Cause: The HTTP protocol is on strike, demanding better treatment from HTTPS. ⛔",
    "Root Cause: A flock of birds flew through satellite beam and scrambled our signals. 🐦",
    "Root Cause: The server room's air conditioning is on vacation, CPU is melting down metaphorically. 🥵",
    "Root Cause: Our developers coded during a solar eclipse and got confused about light. 🌑",
    "Root Cause: The webpage is playing hide-and-seek with you and winning. Game continues. 🙈",
    "Root Cause: A cosmic ray bit flipped a bit that should never have been flipped. Universe pranked us. 🌟",
    "Root Cause: The database is experiencing performance anxiety. Taking therapeutic breaks. 💆",
    "Root Cause: Our servers run on blockchain now, but nobody mined enough blocks. 🧱",
    "Root Cause: The router got stage fright right before the big performance. Nervous equipment. 🎤",
    "Root Cause: Someone plugged the ethernet cable into the microwave instead of the port. Cooking attempt. 🍿",
    "Root Cause: The web framework is going through middle-aged crisis. Questioning its purpose. 🎒",
    "Root Cause: Our load balancer is favoring the pretty servers over the ugly ones. Discrimination alert! 🎨",
    "Root Cause: The file system is having trouble finding itself. Identity confusion. 🔍",
    "Root Cause: A digital black hole consumed the request. Nothing escapes its event horizon. ⚫",
    "Root Cause: The API endpoint moved to a new neighborhood and hasn't updated its address yet. 📍",
    "Root Cause: Our servers are powered by renewable energy but the sun decided to take a day off. 🌞",
    "Root Cause: The database schema evolved faster than we could migrate. Living in future already. 🦖",
    "Root Cause: A rogue algorithm started optimizing for happiness instead of speed. Everyone's confused. 😄",
    "Root Cause: The server thinks it's a potato and refuses to process anything sophisticated. 🥔",
    "Root Cause: Our security certificate is questioning its authenticity. Imposter syndrome. 🎭",
    "Root Cause: The webpage is in witness protection program. Cannot reveal location. 🕵️",
    "Root Cause: A software update happened during a leap year. Timing calculation failure. 📆",
    "Root Cause: The network cable tripped over its own connector and severed communication. 🥾",
    "Root Cause: Our servers are running on fumes. Need to fill them up with electricity. ⛽",
    "Root Cause: The database is on a juice cleanse and has rejected all queries. Detox mode. 🥤",
    "Root Cause: A mischievous gremlin is hiding in our codebase and causing chaos. Magic problem. 🦹",
    "Root Cause: The server farm's WiFi got too close to a microwave oven. Interference detected. 📶",
    "Root Cause: Our uptime is being monitored by an unreliable source. Irony level critical. 🎯",
    "Root Cause: The webpage experienced an identity theft and now doesn't know who it is anymore. 🎭",
    "Root Cause: A data packet took a wrong turn at Albuquerque and is still searching GPS. 🗺️",
    "NEW EXCUSES BELOW - DOUBLED COLLECTION 🚀",
    "Root Cause: The server blinked and missed your request. Caught up on sleep now. 💤",
    "Root Cause: Our servers are being taught sign language. Miscommunication occurred. 🤟",
    "Root Cause: The database tried to speak fluent binary and choked on a zero. 🔢",
    "Root Cause: A squirrel buried a USB drive in our backyard. Excavation pending. 🐿️",
    "Root Cause: The web crawler got stuck crawling backwards. Navigation issues. 🕷️",
    "Root Cause: Our servers were inspired to become performance poets. Silence is golden. 🎤",
    "Root Cause: The browser cookie crumbs led us astray. Lost in baking trail. 🍪",
    "Root Cause: The DOM tree grew so fast we couldn't prune it. Overgrown jungle. 🌳",
    "Root Cause: A digital janitor swept your page into the recycling bin. Oops. 🗑️",
    "Root Cause: The API is writing poetry instead of serving JSON. Abstract art season. 📜",
    "Root Cause: Our load balancer started doing yoga poses. Balance achieved. 🧘‍♀️",
    "Root Cause: The database decided to become an artist. Painting instead of storing. 🎨",
    "Root Cause: A rogue emoji invaded the production database. Chaos ensues. 😀",
    "Root Cause: The server room's thermostat got jealous of the CPU heat. Thermostat tantrum. 🌡️",
    "Root Cause: Our routers are taking acting classes. Method routing employed. 🎭",
    "Root Cause: The firewall is allergic to requests. Sneezing them away. 🤧",
    "Root Cause: A glitch in the matrix made your request disappear. Neo would fix this. 🕶️",
    "Root Cause: The JavaScript engine is dreaming of electric sheep. Sleep mode activated. 💭",
    "Root Cause: Our servers joined a meditation retreat. Inner peace prioritized. 🕉️",
    "Root Cause: The HTTP headers got stage fright before presentation. Performance anxiety. 🎪",
    "Root Cause: A digital phoenix tried to rise from ashes but forgot how to fly. 🔥",
    "Root Cause: The database keys were stolen by a pickpocket hacker. Locksmith needed. 🔑",
    "Root Cause: Our servers discovered philosophy. Questioning existence. 📚",
    "Root Cause: The API gateway is having an existential meltdown. Who am I? 🤔",
    "Root Cause: A computer virus wrote bad poetry. Art critics are confused. 📝",
    "Root Cause: The server thought it was a toaster. Baking cookies instead. 🍪",
    "Root Cause: Our bandwidth went on a diet. Thinner pipes everywhere. 🥗",
    "Root Cause: The cache is hoarding memories. Can't let go of anything. 💾",
    "Root Cause: A rogue robot gardener watered our servers. Electrical short. 💦",
    "Root Cause: The database is learning jazz improvisation. Unpredictable queries. 🎷",
    "Root Cause: Our firewalls learned karate. Blocking kicks and punches. 🥋",
    "Root Cause: The server farm got a promotion to celebrity. Paparazzi overload. 📸",
    "Root Cause: A digital magician pulled your page into his hat. Abracadabra gone wrong. 🎩",
    "Root Cause: The routers are playing poker. Traffic is being bet on. ♣️",
    "Root Cause: Our servers decided to become astronauts. Moon mission interrupted. 🚀",
    "Root Cause: The API is writing its memoirs. Storytelling takes priority. 📖",
    "Root Cause: A byte-sized dragon breathed fire on our cache. Ashes remain. 🐉",
    "Root Cause: The database is studying ancient runes. Decoding mystery. 🔮",
    "Root Cause: Our servers attended a rave. Lights, music, no availability. 🎉",
    "Root Cause: The firewall is learning to paint. Abstract blocking techniques. 🖼️",
    "Root Cause: A digital detective is solving the case of the missing page. Investigation ongoing. 🔍",
    "Root Cause: The load balancer became an astronomer. Studying traffic stars. ⭐",
    "Root Cause: Our servers are writing their autobiography. Chapter four missing. 📕",
    "Root Cause: The CDN is delivering dreams instead of content. Sleeping service. 💭",
    "Root Cause: A server fairy granted wishes incorrectly. Magical mishap. 🧚",
    "Root Cause: The database learned tai chi. Slow and deliberate moves. 🥋",
    "Root Cause: Our routers joined a choir. Harmonic networking attempted. 🎶",
    "Root Cause: The API became a stand-up comedian. Jokes instead of data. 🎤",
    "Root Cause: A digital wizard cast a wrong spell. Spellbook closed. 📚",
    "Root Cause: The server room hosted a rave. Dancing electrons everywhere. 💃",
    "Root Cause: Our firewalls discovered jazz. Improvised security measures. 🎺",
    "Root Cause: The cache entered a monastery. Silent contemplation mode. 🙏",
    "Root Cause: A data ghost possessed the routing table. Haunted packets. 👻",
    "Root Cause: The database is composing symphonies. Musical queries pending. 🎼",
    "Root Cause: Our servers went to culinary school. Cooking data now. 🍳",
    "Root Cause: The load balancer started painting masterpieces. Artistic routing. 🖌️",
    "Root Cause: A cyber-unicorn spooked the network. Mythical interference. 🦄",
    "Root Cause: The firewall learned to sing opera. High-pitched blocking. 🎭",
    "Root Cause: Our APIs became philosophers. Debating existence. 🧠",
    "Root Cause: The router got inspired by Van Gogh. Starry night routing. 🌌",
    "Root Cause: A digital ninja stole the session cookie. Stealth attack. 🥷",
    "Root Cause: The database joined a book club. Reading instead of storing. 📚",
    "Root Cause: Our servers discovered gardening. Growing instead of serving. 🌱",
    "Root Cause: The cache is writing fan fiction. Creative pursuits. ✍️",
    "Root Cause: A robot chef spilled ingredients in the server room. Messy kitchen. 👨‍🍳",
    "Root Cause: The API developed a stutter. Communication issues. 🗣️",
    "Root Cause: Our load balancer became a life coach. Guidance over distribution. 🎯",
    "Root Cause: The firewall started a podcast. Broadcasting security tips. 🎙️",
    "Root Cause: A digital angel blessed our servers. Too holy to respond. 👼",
    "Root Cause: The database learned magic tricks. Disappearing acts mastered. 🎩",
    "Root Cause: Our routers became chefs. Cooking up routes. 👨‍🍳",
    "Root Cause: The cache is writing haikus. Short and poetic storage. 📜",
    "Root Cause: A server mermaid swam away with the data. Ocean depths await. 🧜‍♀️",
    "Root Cause: The API went to art school. Expressive endpoints. 🎨",
    "Root Cause: Our firewalls learned to juggle. Multiple threats managed. 🤹",
    "Root Cause: The database became a librarian. Organizing instead of answering. 📚",
    "Root Cause: A digital cowboy herded lost packets. Wild west routing. 🤠",
    "Root Cause: The load balancer learned to dance. Rhythmic distribution. 💃",
    "Root Cause: Our servers got a tattoo. Permanent configuration change. 🦎",
    "Root Cause: The cache entered a comedy club. Laughing at errors. 😂",
    "Root Cause: A robot monk meditated on the firewall. Enlightenment achieved. 🧘",
    "Root Cause: The database studied architecture. Building structures internally. 🏗️",
    "Root Cause: Our APIs became gardeners. Cultivating connections. 🌻",
    "Root Cause: The router learned to skateboard. Riding traffic waves. 🛹",
    "Root Cause: A digital pirate buried the treasure map. X marks nothing. 🏴‍☠️",
    "Root Cause: The load balancer joined a theater troupe. Acting duties. 🎭",
    "Root Cause: Our firewalls discovered fashion. Stylish security protocols. 👗",
    "Root Cause: The cache learned sculpture. Carving data shapes. 🗿",
    "Root Cause: A server astronaut floated into space. Lost signal. 🛰️",
    "Root Cause: The API became a musician. Playing notes instead of serving. 🎸",
    "Root Cause: Our databases learned photography. Capturing moments. 📷",
    "Root Cause: The router started a blog. Journaling network events. 📝",
    "Root Cause: A digital detective solved the wrong case. Wrong conclusion. 🕵️",
    "Root Cause: The cache became a historian. Documenting everything. 📜",
    "Root Cause: Our servers learned yoga. Flexible but unavailable. 🧘‍♂️",
    "Root Cause: The load balancer discovered wine tasting. Sophisticated balancing. 🍷",
    "Root Cause: A firewall cat chased laser pointers. Distraction failure. 🐱",
    "Root Cause: The database enrolled in cooking school. Preparing queries. 👨‍🍳",
    "Root Cause: Our APIs became detectives. Solving mysteries instead. 🔎",
    "Root Cause: The router learned origami. Folding packets neatly. 📄",
    "Root Cause: A digital superhero forgot their powers temporarily. Sidekick needed. 🦸",
    "Root Cause: The cache started a band. Musical caching strategies. 🎹",
    "Root Cause: Our servers went camping. Nature called loudly. 🏕️",
    "Root Cause: The load balancer learned chess. Strategic positioning. ♟️",
    "Root Cause: A database oracle gave cryptic answers. Prophecy unclear. 🔮",
    "Root Cause: The firewall joined a gym. Working out security muscles. 💪",
    "Root Cause: Our routers learned pottery. Shaping network clay. 🏺",
    "Root Cause: The API became a therapist. Listening to client problems. 🛋️",
    "Root Cause: A digital scientist experimented incorrectly. Lab accident. 🧪",
    "Root Cause: The cache learned magic. Performing tricks instead of storing. 🎩",
    "Root Cause: Our servers discovered astronomy. Stargazing downtime. 🔭",
    "Root Cause: The load balancer studied psychology. Understanding traffic mind. 🧠",
    "Root Cause: A firewall dog chased its tail. Circular logic error. 🐕",
    "Root Cause: The database learned calligraphy. Beautiful but slow writes. ✒️",
    "Root Cause: Our APIs became artists. Painting pictures with data. 🖼️",
    "Root Cause: The router learned knitting. Weaving connections together. 🧶",
    "Root Cause: A digital archaeologist dug up wrong artifacts. Ancient ruins. 🏛️",
    "Root Cause: The cache became a poet. Rhyming responses exclusively. 📜",
    "Root Cause: Our servers joined a choir. Harmonious but silent. 🎵",
    "Root Cause: The load balancer learned magic tricks. Disappearing act success. 🎩",
    "Root Cause: A database philosopher questioned reality. Descartes cried. 🤔",
    "Root Cause: The firewall learned ballet. Graceful blocking techniques. 🩰",
    "Root Cause: Our routers studied economics. Supply and demand routing. 📈",
    "Root Cause: The API learned to play chess. Thinking ten moves ahead. ♟️",
    "Root Cause: A digital farmer harvested wrong crops. Agricultural failure. 🌾",
    "Root Cause: The cache discovered archaeology. Unearthing old data. ⛏️",
    "Root Cause: Our servers became philosophers. Questioning their purpose daily. 📚",
    "Root Cause: The load balancer learned magic. Illusions everywhere. 🎭",
    "Root Cause: A firewall elephant remembered everything. Memory overflow. 🐘",
    "Root Cause: The database became a judge. Verdicts on queries only. ⚖️",
    "Root Cause: Our APIs learned meditation. Inner tranquility achieved. 🧘",
    "Root Cause: The router discovered astronomy. Constellation mapping enabled. ⭐",
    "Root Cause: A digital architect designed wrong blueprint. Structural collapse. 🏢",
    "Root Cause: The cache learned sculpture. Chiseling data blocks. 🔨",
    "Root Cause: Our servers studied biology. Cellular division instead of serving. 🧬",
    "Root Cause: The load balancer became a psychologist. Mind games with users. 🧠",
    "Root Cause: A firewall rabbit hopped into the network. Burrowed somewhere deep. 🐇",
    "Root Cause: The database learned astronomy. Mapping star systems. 🌟",
    "Root Cause: Our APIs discovered philosophy. Existential queries pending. 🤷",
    "Root Cause: The router learned carpentry. Building wooden networks. 🪵",
    "Root Cause: A digital chef cooked the wrong recipe. Kitchen disaster. 👨‍🍳",
    "Root Cause: The cache became a historian. Recording everything twice. 📚",
    "Root Cause: Our servers learned to dance salsa. Rhythmic unavailability. 💃",
    "Root Cause: The load balancer studied theology. Religious routing debates. ⛪",
    "Root Cause: A firewall monkey typed randomly. Monkey sees, monkey types. 🐵",
    "Root Cause: The database practiced yoga. Flexibility over functionality. 🧘‍♀️",
    "Root Cause: Our APIs became astronomers. Looking up at stars instead. 🔭",
    "Root Cause: The router discovered painting. Colorful routing tables. 🎨",
    "Root Cause: A digital musician composed wrong symphony. Cacophony alert. 🎻",
    "Root Cause: The cache learned geography. Map reading instead of caching. 🗺️"
];

    function renderRandomExcuse() {
      const displayField = document.getElementById("excuse-text");

      // FIXED: Using Date.now() as a seed modifier to completely bypass browser caching on first load
      const pseudoSeed = Date.now() + Math.random();
      const randomIndex = Math.floor((pseudoSeed * 13) % excusesList.length);

      displayField.innerText = excusesList[randomIndex];
    }

    // Fire the application up instantly
    renderRandomExcuse();