  const excusesList = [
    "Root Cause: A hamster chewed through the main optical cable. Technicians are currently feeding it. 🐹",
    "Root Cause: The website's AI submitted a vacation request and is currently relaxing on a virtual beach. 🌴",
    "Root Cause: This page exists, but only in an alternate dimension. Please recalibrate your quantum tuner. 🌌",
    "Root Cause: Spilled coffee onto the primary mainframe. The server is still shaking from the caffeine. ☕",
    "Root Cause: The administrator took the code home and accidentally left it on the public bus. 🚌",
    "Root Cause: Critical disruption in the space-time continuum. Please take three steps away from the monitor. 🕳️",
    "Root Cause: Solar flares are actively reorganizing our data index packages into random emojis. ☀️",
    "Root Cause: The server gnome is currently sleeping on the requested database sector. 🧝",
    "Root Cause: A rogue pixel escaped its rendering queue and caused a cascade failure. 🔲",
    "Root Cause: The cloud storage is actually just someone's laptop named 'Cloud'. It crashed. 💻",
    "Root Cause: Our firewall caught a cold and blocked all legitimate traffic by accident. 🤧",
    "Root Cause: The database forgot its own password and locked itself out permanently. 🔐",
    "Root Cause: An intern unplugged the 'server' thinking it was a space heater. ❄️",
    "Root Cause: The CDN got lost trying to find its way back from the content delivery trip. 🗺️",
    "Root Cause: DNS servers are undergoing existential therapy. They question their purpose. 🧘",
    "Root Cause: The load balancer distributed traffic unevenly, now one server is depressed. ⚖️",
    "Root Cause: A backup generator tried to backup a file that was already backed up. 🔄",
    "Root Cause: The cache expired so aggressively it deleted itself along with everything else. 🗑️",
    "Root Cause: Our uptime monitoring service is down, ironically monitoring its own outage. 📉",
    "Root Cause: A microservice had a microbreakdown. It's taking a micro-vacation. 🔬",
    "Root Cause: The API received too many compliments and decided to take a nap. 😴",
    "Root Cause: Bandwidth ran out halfway through loading this error message. You got cut off mid-crisis. 📶",
    "Root Cause: SSL certificates got confused about which identity to prove during verification. 🛂",
    "Root Cause: Git merge conflict on production. Someone typed 'theirs' instead of 'ours'. 🌳",
    "Root Cause: The web socket disconnected to go do some soul-searching. It'll be back. 🔌",
    "Root Cause: Container orchestration failed because the containers refused to dock. ⚓",
    "Root Cause: Load testing was too successful. The system now fears actual traffic. 🏋️",
    "Root Cause: The motherboard went on strike demanding better working conditions. ⚡",
    "Root Cause: We're experiencing an unexpected shortage of zeros and ones. 📊",
    "Root Cause: The router thinks it's a fish and needs water. 🐟",
    "Root Cause: A meteorite narrowly missed our data center, but scared the servers badly. ☄️",
    "Root Cause: The keyboard sent us a strongly worded letter. We're negotiating. ⌨️",
    "Root Cause: Cat walked across the server during critical update. Damage assessment ongoing. 🐱",
    "Root Cause: The firewall is having an identity crisis. Is it fire? Is it wall? Nobody knows. 🤷",
    "Root Cause: Server room temperature reached 'slightly warm' levels. Panic ensued. 🌡️",
    "Root Cause: The database is on a digital detox and refusing to connect. 📵",
    "Root Cause: Our IT department is currently being held hostage by ransomware. Just kidding, they're at lunch. 🥪",
    "Root Cause: The page got stuck in traffic on the information superhighway. 🛣️",
    "Root Cause: Binary code went on hunger strike. We're trying to feed it more bits. 🍔",
    "Root Cause: The hosting company's power went out, but the lights stayed on, confusing everyone. 💡",
    "Root Cause: An alien signal corrupted our CSS. Now everything looks extraterrestrial. 👽",
    "Root Cause: The webpage went on a journey of self-discovery and forgot where it lives. ✨",
    "Root Cause: Our servers are speaking in riddles today. Try asking them nicer questions. 🎭",
    "Root Cause: The internet decided to take a mental health day. It's been stressed lately. 🧠",
    "Root Cause: A ghost in the machine is haunting our database tables. 👻",
    "Root Cause: The HTML tag got lost looking for its closing sibling. Family drama. 👨‍👩‍👦",
    "Root Cause: Cloud provider's cloud literally turned into rain. Servers flooded. ☁️",
    "Root Cause: The API key was stolen by a cyber-ninja. We're tracking them down. 🥷",
    "Root Cause: Quantum entanglement glitched and the page is now in two places at once. ⚛️",
    "Root Cause: Our developer's coffee cup tipped over during commit. Code is soggy. ☕",
    "Root Cause: The server thinks it's Tuesday when it's actually Friday. Confused days. 📅",
    "Root Cause: WiFi waves are interfering with each other. Creating digital storm. ⛈️",
    "Root Cause: The URL became shy and hid behind the http prefix. 😳",
    "Root Cause: A butterfly flapped its wings in China and our server farm collapsed. 🦋",
    "Root Cause: The login form fell in love with the logout button and eloped. 💕",
    "Root Cause: Our backup server backed up so much it became a hoarder. Can't fit anything else. 📦",
    "Root Cause: The database is going through a rebellious phase. Ignores all queries. 🤬",
    "Root Cause: Someone accidentally pressed the universe's delete button. Cosmic mistake. 🌌",
    "Root Cause: The cache memory had an existential crisis and emptied itself. Philosophical moment. 🤔",
    "Root Cause: Our servers are powered by hamsters. They're tired today. Running wheel jammed. 🐭",
    "Root Cause: The internet explorer (yes, really) showed up uninvited and broke things. 🌐",
    "Root Cause: A time traveler from the future deleted this page to save us from ourselves. ⏰",
    "Root Cause: The CSS styles went on vacation without telling the HTML. Awkward breakup. 👢",
    "Root Cause: Our servers are listening to heavy metal music and got distracted by the guitar solos. 🎸",
    "Root Cause: The JavaScript interpreter decided to interpret literally. No creativity allowed. 🤖",
    "Root Cause: A digital virus is making everything feel sick. Prescribed bed rest. 🦠",
    "Root Cause: The server farm's wifi-connected chickens laid eggs that crashed the system. 🐔",
    "Root Cause: Our firewall is afraid of hackers and locked itself in panic mode. 🚪",
    "Root Cause: The database indexes got tangled like headphones in a pocket. Unraveling slowly. 🎧",
    "Root Cause: Someone's smart fridge is spamming requests and overwhelming our servers. 🧊",
    "Root Cause: The web server is practicing mindfulness and ignoring incoming requests for inner peace. 🧘",
    "Root Cause: Our CDN is delivering clouds instead of content. Weather-dependent service. 🌧️",
    "Root Cause: The code underwent a spiritual transformation and transcended physical existence. 🙏",
    "Root Cause: A typo in the production server created a parallel universe where this page doesn't exist. 🌀",
    "Root Cause: The server is currently training for a marathon. Too busy running to serve pages. 🏃",
    "Root Cause: Our hosting provider's hosting provider's hosting provider is down. Infinite nesting failure. 🎭",
    "Root Cause: The HTTP protocol is on strike, demanding better treatment from HTTPS. ⛔",
    "Root Cause: A flock of birds flew through satellite beam and scrambled our signals. 🐦",
    "Root Cause: The server room's air conditioning is on vacation, CPU is melting down metaphorically. 🥵",
    "Root Cause: Our developers coded during a solar eclipse and got confused about light. 🌑",
    "Root Cause: The webpage is playing hide-and-seek with you and winning. Game continues. 🙈",
    "Root Cause: A cosmic ray bit flipped a bit that should never have been flipped. Universe pranked us. 🌟",
    "Root Cause: The database is experiencing performance anxiety. Taking therapeutic breaks. 💆",
    "Root Cause: Our servers run on blockchain now, but nobody mined enough blocks. 🧱",
    "Root Cause: The router got stage fright right before the big performance. Nervous equipment. 🎤",
    "Root Cause: Someone plugged the ethernet cable into the microwave instead of the port. Cooking attempt. 🍿",
    "Root Cause: The web framework is going through middle-aged crisis. Questioning its purpose. 🎒",
    "Root Cause: Our load balancer is favoring the pretty servers over the ugly ones. Discrimination alert! 🎨",
    "Root Cause: The file system is having trouble finding itself. Identity confusion. 🔍",
    "Root Cause: A digital black hole consumed the request. Nothing escapes its event horizon. ⚫",
    "Root Cause: The API endpoint moved to a new neighborhood and hasn't updated its address yet. 📍",
    "Root Cause: Our servers are powered by renewable energy but the sun decided to take a day off. 🌞",
    "Root Cause: The database schema evolved faster than we could migrate. Living in future already. 🦖",
    "Root Cause: A rogue algorithm started optimizing for happiness instead of speed. Everyone's confused. 😄",
    "Root Cause: The server thinks it's a potato and refuses to process anything sophisticated. 🥔",
    "Root Cause: Our security certificate is questioning its authenticity. Imposter syndrome. 🎭",
    "Root Cause: The webpage is in witness protection program. Cannot reveal location. 🕵️",
    "Root Cause: A software update happened during a leap year. Timing calculation failure. 📆",
    "Root Cause: The network cable tripped over its own connector and severed communication. 🥾",
    "Root Cause: Our servers are running on fumes. Need to fill them up with electricity. ⛽",
    "Root Cause: The database is on a juice cleanse and has rejected all queries. Detox mode. 🥤",
    "Root Cause: A mischievous gremlin is hiding in our codebase and causing chaos. Magic problem. 🦹",
    "Root Cause: The server farm's WiFi got too close to a microwave oven. Interference detected. 📶",
    "Root Cause: Our uptime is being monitored by an unreliable source. Irony level critical. 🎯",
    "Root Cause: The webpage experienced an identity theft and now doesn't know who it is anymore. 🎭",
    "Root Cause: A data packet took a wrong turn at Albuquerque and is still searching GPS. 🗺️"
  ];

    function renderRandomExcuse() {
      const displayField = document.getElementById("excuse-text");

      // FIXED: Using Date.now() as a seed modifier to completely bypass browser caching on first load
      const pseudoSeed = Date.now() + Math.random();
      const randomIndex = Math.floor((pseudoSeed * 13) % excusesList.length);

      displayField.innerText = excusesList[randomIndex];
    }

    // Fire the application up instantly
    renderRandomExcuse();