name: Auto Update Timestamp
permissions:
  contents: write
on:
  push:
    paths:
      - 'script.js'

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Insert current date
        run: |
          CURRENT_DATE="Updated $(date -u +'%d %B %Y')"
          sed -i "s|<!-- LAST_UPDATE_HERE -->|<!-- LAST_UPDATE_HERE -->$CURRENT_DATE|g" index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git add index.html
          git commit -m "chore: update timestamp in index.html [skip ci]" || echo "No changes to commit"
          git push
